version: "3.7"

services:
  travel_goals_api:
    image: postgres
    container_name: travel_goals_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=travel_goals_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: travel_goals_api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - travel_goals_api
    depends_on:
      - travel_goals_api


volumes:
  pgdata:
    driver: local
